# Generated by Django 3.1.1 on 2020-11-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droitsprofils',
            name='aucun',
        ),
    ]
