# Generated by Django 3.1.1 on 2020-10-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='prenom_du_parent',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
