# Generated by Django 3.1.7 on 2021-03-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_nom', models.CharField(max_length=100, null=True, verbose_name='Nom du pack')),
                ('nouveau_nom', models.CharField(max_length=100, null=True, verbose_name='Nom du pack')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('jours', models.IntegerField(default=100, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='dix_milles',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='jours_ouvrables',
            field=models.IntegerField(default=0, null=True, verbose_name='Durée du contrat'),
        ),
        migrations.AddField(
            model_name='user',
            name='point_a_affecter',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='espace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.packs'),
        ),
    ]
