# Generated by Django 3.1.1 on 2020-10-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nb_pers_amene',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
