# Generated by Django 3.1.3 on 2021-02-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='longueur_audio1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='longueur_audio2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='longueur_audio3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='longueur_audio4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='longueur_audio5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='longueur_video10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='longueur_video6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='longueur_video7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='longueur_video8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='longueur_video9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='temps_lu_audio1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='temps_lu_audio2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='temps_lu_audio3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='temps_lu_audio4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='temps_lu_audio5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='temps_lu_video10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='temps_lu_video6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='temps_lu_video7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='temps_lu_video8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='temps_lu_video9',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
