# Generated by Django 3.1.4 on 2020-12-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.profils'),
        ),
    ]
