# Generated by Django 3.1.1 on 2020-10-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0002_parent_prenom_du_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='code_du_parent',
            new_name='code_du_parrain',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='nom_du_parent',
            new_name='nom_du_parrain',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='prenom_du_parent',
            new_name='prenom_du_parrain',
        ),
    ]
