# Generated by Django 3.1.4 on 2020-12-28 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0002_auto_20201228_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.profils'),
        ),
    ]
