# Generated by Django 3.1.1 on 2020-11-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0002_user_nom_du_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
