# Generated by Django 3.1.1 on 2020-11-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0002_remove_droitsprofils_aucun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('prenom', models.CharField(max_length=255, null=True)),
                ('telephone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
