# Generated by Django 3.1.4 on 2020-12-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0003_auto_20201228_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gam',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
