# Generated by Django 3.1.1 on 2020-11-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0003_wara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(null=True)),
                ('archive', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='nom_d_utilisateur',
            field=models.CharField(help_text="Le nom d'utilisateur servira à se connecter à la plateforme, également pour parrainer un membre. Ex. toto21", max_length=255, null=True, unique=True),
        ),
    ]
