# Generated by Django 3.1.7 on 2021-04-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0003_auto_20210409_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='pdf4',
            field=models.FileField(blank=True, null=True, upload_to='wara/%y %m %d', verbose_name='Fichier pdf 4'),
        ),
        migrations.AddField(
            model_name='modules',
            name='pdf5',
            field=models.FileField(blank=True, null=True, upload_to='wara/%y %m %d', verbose_name='Fichier pdf 5'),
        ),
    ]
