# Generated by Django 3.1.4 on 2020-12-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0004_auto_20201228_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
