# Generated by Django 3.1.7 on 2021-04-12 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0005_auto_20210409_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True, verbose_name='Nom de la catégorie')),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie du forum',
                'verbose_name_plural': 'Catégories des forums',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, null=True, verbose_name='Titre du forum')),
                ('intitule', models.TextField(null=True, verbose_name='Description du forum')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.categorieforum')),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forums',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SujetForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, null=True, verbose_name='Titre du sujet')),
                ('messages', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.forums')),
            ],
            options={
                'verbose_name': 'Sujet du forum',
                'verbose_name_plural': 'Sujets des forums',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MessagesSujetsForums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sujet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.sujetforum')),
            ],
            options={
                'verbose_name': 'Message pour ce sujet',
                'verbose_name_plural': 'Messages pour les sujets',
                'ordering': ('id',),
            },
        ),
    ]
