# Generated by Django 3.1.7 on 2021-04-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0006_categorieforum_forums_messagessujetsforums_sujetforum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forums',
            name='categorie',
        ),
        migrations.AddField(
            model_name='forums',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.versions'),
        ),
    ]
