# Generated by Django 3.1.7 on 2021-04-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0007_auto_20210414_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forums',
            name='version',
        ),
        migrations.AddField(
            model_name='forums',
            name='vague',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.vague'),
        ),
    ]
