# Generated by Django 3.1.7 on 2021-04-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0008_auto_20210414_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vague',
            options={'ordering': ('id',), 'verbose_name': 'Vague', 'verbose_name_plural': 'Vagues'},
        ),
        migrations.AlterField(
            model_name='packs',
            name='ancien_nom',
            field=models.CharField(max_length=100, null=True, verbose_name='Ancien nom du pack'),
        ),
        migrations.AlterField(
            model_name='user',
            name='jours_ouvrables',
            field=models.IntegerField(default=100, null=True, verbose_name='Durée du contrat'),
        ),
    ]
