# Generated by Django 3.1.7 on 2021-04-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0009_auto_20210418_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_achat_espace',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
