# Generated by Django 3.2 on 2021-06-10 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0010_user_date_achat_espace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_de_jgk', models.ImageField(blank=True, null=True, upload_to='fichier-attestation/%y %m %d', verbose_name='logo')),
                ('administrateur', models.ImageField(blank=True, null=True, upload_to='fichier-attestation/%y %m %d', verbose_name='administrateur')),
                ('signature_de_jgk', models.ImageField(blank=True, null=True, upload_to='fichier-attestation/%y %m %d', verbose_name='signature')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attestation',
                'verbose_name_plural': 'Attestations',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AttestionMembre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestation', models.ImageField(blank=True, null=True, upload_to='attestations/%y %m %d', verbose_name='attestation')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attestation des membres',
                'verbose_name_plural': 'Attestations des membres',
                'ordering': ('id',),
            },
        ),
    ]
